package com.gtime.general

object Constants {
    const val CACHE_ACC = "CACHE_ACC"
    const val TIME_OF_ALL = "ALL_TIME"
    const val KEY_LIFE = "KEY_LIFE"
    const val CACHE_INT = "CacheInt"
    const val SCORE_TABLE = "score_table"
    const val CACHE_BOOLEANS = "CacheBooleans"
    const val KEY_FIRST_LAUNCH = "FirstLaunch"
    const val KEY_HARDCORE_MODE = "HardcoreMode"
    const val KEY_NORMAL_MODE = "NormalMode"
    const val KEY_ACHIEVEMENT_HARDCORE = "AchievementHardcore"
    const val KEY_IS_LOST_HARDCORE = "IsLostHardcore"
    const val ADAPTER_HARMFUL = "AdapterHarmful"
    const val ADAPTER_USEFUL = "AdapterUseful"
    const val ADAPTER_OTHERS = "AdapterOthers"
    const val DAILY_STATS_WORKER = "DAILY_STATS_WORKER"
    const val INC_LIFE_WORKER = "INC_LIFE_WORKER"
    const val APP_TABLE = "app_table"
    const val EMAIL = "email"
    const val DISPLAY_NAME = "display_name"
    const val AVATAR_ID = "avatar_id"
    const val AVATAR_URL_START = "https://avatars.yandex.net/get-yapic/"
    const val AVATAR_URL_END = "/islands-68"
    const val KEY_NAME="KEY_NAME"
    const val KEY_EMAIL="KEY_EMAIL"
    const val KEY_URL="KEY_URL"
    const val IS_ONLINE = "IS_ONLINE"
}